session:
  redis:
    host:
    port:
    db:
    pass:
    secret:


db:
    host:
    port:
    user:
    pass:
    name:

mail:
    smtp:
        user:
        pass:
        host:
        secureConnection:
        port:

google:
    clientID:
    clientSecret:
    callbackURL:
    passReqToCallback: